#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Build the pinned borg 2 reference interpreter (plan task 0.7).
#
# borge's correctness is defined as interoperability with a *specific* borg, not with
# whatever borg happens to be installed. The system borg here is 1.2.8, which cannot
# read the borg 2 repository format borge targets, so every differential and interop
# test drives the interpreter this script builds.
#
# The upstream commit is pinned in internal/version/version.go and asserted below.
# Rebasing onto a newer upstream commit is a deliberate, reviewed activity - if this
# script's assertion fires, that is the point, not an inconvenience.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"

BORG_SRC="${BORGE_BORG_SRC:-/home/renes/projects/borg}"
VENV="${BORGE_BORG2_VENV:-$ROOT/.venv-borg2}"
PINNED=$(sed -n 's/.*BorgUpstreamCommit *= *"\([0-9a-f]*\)".*/\1/p' "$ROOT/internal/version/version.go")

die() { printf 'setup.sh: %s\n' "$*" >&2; exit 1; }

[ -n "$PINNED" ] || die "could not read BorgUpstreamCommit from internal/version/version.go"
[ -d "$BORG_SRC/.git" ] || die "no borg checkout at $BORG_SRC (set BORGE_BORG_SRC)"

actual=$(git -C "$BORG_SRC" rev-parse HEAD)
if [ "$actual" != "$PINNED" ]; then
    cat >&2 <<EOF
setup.sh: borg checkout is not at the pinned commit.

  pinned (internal/version/version.go): $PINNED
  checkout ($BORG_SRC):                 $actual

The interoperability gate in docs/PORTING_PLAN.md section 10 only means something
against a fixed upstream. Either check the pinned commit out:

  git -C $BORG_SRC checkout $PINNED

or, if moving the pin is intended, update BorgUpstreamCommit/BorgUpstreamDate and
review the upstream diff for format changes before re-running.
EOF
    exit 1
fi

echo "setup.sh: borg checkout at pinned commit ${PINNED:0:12}"

python3 -m venv "$VENV"
# shellcheck disable=SC1091
source "$VENV/bin/activate"

python -m pip install --quiet --upgrade pip setuptools wheel setuptools_scm

# borg 2 needs these beyond what pyproject.toml pulls in automatically:
#   borghash  - the ChunkIndex hash table, split out of borg (borge ports it in stage 1.6)
#   borgstore - the object store layer  (borge ports it in stage 2)
# Both are Borg Collective projects; their licenses are recorded by
# scripts/check-upstream-licenses.sh (plan task 0.8) before any of their code is read.
python -m pip install --quiet "borghash" "borgstore[rest,blake3]~=0.6.0"

# Editable install so the venv tracks the checkout without copying it.
python -m pip install --quiet -e "$BORG_SRC"

python -m pip freeze --exclude-editable > "$HERE/requirements.lock"
git -C "$BORG_SRC" rev-parse HEAD > "$HERE/borg-commit.txt"

cat > "$HERE/borg2" <<EOF
#!/usr/bin/env bash
# Generated by tests/borg2/setup.sh - the pinned borg 2 reference interpreter.
# Its cache and config are kept apart from any real borg installation on this
# machine, so a test run can never disturb the user's own repositories.
set -euo pipefail
export BORG_BASE_DIR="\${BORG_BASE_DIR:-$ROOT/.venv-borg2/base}"
mkdir -p "\$BORG_BASE_DIR"
exec "$VENV/bin/borg" "\$@"
EOF
chmod +x "$HERE/borg2"

echo "setup.sh: $("$HERE/borg2" --version)"
echo "setup.sh: wrote $HERE/requirements.lock, $HERE/borg-commit.txt, $HERE/borg2"
