// SPDX-License-Identifier: Apache-2.0

package msgpackx

import (
	"bufio"
	"encoding/hex"
	"os"
	"strings"
	"testing"
)

// The differential test against msgpack-python, via fixtures generated by borg's own
// msgpack wrapper (testdata/gen_fixtures.py, run through the pinned borg 2 venv).
//
// Decode-then-re-encode is deliberately the whole test. Requiring the bytes back
// unchanged checks both directions at once and needs no way to express a Python value
// in Go: borge must accept every form borg emits, and must independently choose the
// same form when it writes. A unit test written from the same misunderstanding as the
// implementation would pass; this cannot.

type fixture struct {
	name  string
	bytes []byte
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	f, err := os.Open("testdata/fixtures.txt")
	if err != nil {
		t.Fatalf("cannot read fixtures (regenerate with 'make msgpack-fixtures'): %v", err)
	}
	defer f.Close()

	var out []fixture
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<24)
	for line := 1; sc.Scan(); line++ {
		text := sc.Text()
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		name, hexed, ok := strings.Cut(text, "\t")
		if !ok {
			t.Fatalf("testdata/fixtures.txt:%d: expected '<name>\\t<hex>'", line)
		}
		raw, err := hex.DecodeString(hexed)
		if err != nil {
			t.Fatalf("testdata/fixtures.txt:%d (%s): bad hex: %v", line, name, err)
		}
		out = append(out, fixture{name: name, bytes: raw})
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if len(out) == 0 {
		t.Fatal("testdata/fixtures.txt contains no fixtures")
	}
	return out
}

// TestFixtureRoundTrip is the stage 1.1 gate: every fixture decodes, and re-encoding
// the decoded value reproduces borg's bytes exactly.
func TestFixtureRoundTrip(t *testing.T) {
	fixtures := loadFixtures(t)
	t.Logf("checking %d fixtures produced by msgpack-python via borg", len(fixtures))

	for _, f := range fixtures {
		t.Run(f.name, func(t *testing.T) {
			v, err := Unmarshal(f.bytes)
			if err != nil {
				t.Fatalf("decode failed: %v\n  borg bytes: %x", err, f.bytes)
			}

			// A map decoded from the wire has no Stable flag, so re-encoding preserves
			// the order borg wrote. That is the correct behaviour for a re-encode: the
			// sort belongs to construction time, not to transport.
			got, err := Marshal(v)
			if err != nil {
				t.Fatalf("re-encode failed: %v (decoded as %T)", err, v)
			}
			if string(got) != string(f.bytes) {
				t.Errorf("re-encode differs from borg\n  borg:  %x\n  borge: %x\n  value: %T %v",
					f.bytes, got, v, v)
			}
		})
	}
}

// TestFixtureDecodeConsumesEverything guards against a decoder that stops early and
// silently ignores the rest - which would look like a successful round trip for a
// prefix while dropping data.
func TestFixtureDecodeConsumesEverything(t *testing.T) {
	for _, f := range loadFixtures(t) {
		d := NewDecoder(f.bytes)
		if _, err := d.Decode(); err != nil {
			t.Fatalf("%s: %v", f.name, err)
		}
		if d.Remaining() != 0 {
			t.Errorf("%s: decoder left %d of %d byte(s) unconsumed", f.name, d.Remaining(), len(f.bytes))
		}
	}
}

// TestFixtureTruncatedIsRejected feeds every prefix of every fixture to the decoder.
// None may panic, and none may report success, because a truncated object is exactly
// what a torn write or a corrupt pack looks like.
func TestFixtureTruncatedIsRejected(t *testing.T) {
	for _, f := range loadFixtures(t) {
		if len(f.bytes) < 2 {
			continue
		}
		for n := 1; n < len(f.bytes); n++ {
			v, err := Unmarshal(f.bytes[:n])
			if err == nil {
				t.Errorf("%s: %d-byte prefix of a %d-byte value decoded without error as %T %v",
					f.name, n, len(f.bytes), v, v)
			}
		}
	}
}

// TestFixtureCorruptedDoesNotPanic flips bytes and requires the decoder to either
// decode something or report an error - never crash. A backup tool reads attacker- or
// hardware-corrupted bytes as a matter of course.
func TestFixtureCorruptedDoesNotPanic(t *testing.T) {
	for _, f := range loadFixtures(t) {
		for i := range f.bytes {
			for _, mask := range []byte{0xff, 0x01, 0x80} {
				corrupt := append([]byte(nil), f.bytes...)
				corrupt[i] ^= mask
				func() {
					defer func() {
						if r := recover(); r != nil {
							t.Fatalf("%s: panic on corrupted input (byte %d ^= 0x%02x): %v",
								f.name, i, mask, r)
						}
					}()
					_, _ = Unmarshal(corrupt)
				}()
			}
		}
	}
}
